### ISSUE TITLE
Get Function showing wrong values after first calls and then the right one

### ISSUE THREAD

**Issue by heikone** [do-gooder/rctpower_writesupport#1]
Hi, I've observed, that the call of the function `get_value` sometimes delivers strings values and after a couple of calls the expected value (here: 0.75) is delivered.

Refer to my example:
![image](https://github.com/user-attachments/assets/a461d915-6bef-4c5b-b736-ff982382f0eb)

@do-gooder, can you confirm this behaviour?

**Comment by do-gooder** [comment]
@heikone, do you have an app or, for example, the Home Assistant integration running?
Perhaps the RCT portal could also be causing the problem.

For me, the problem usually occurs when other requests are running at the same time.

**Comment by heikone** [comment]
Good point. App might be getting values and Homeassistant custom integration [rct-power-integration](https://github.com/weltenwort/home-assistant-rct-power-integration) is running. 
Thanks, Heiko

**Comment by heikone** [comment]
Confirmed. When app and integration deactivated, the values are directly as expected.
