### ISSUE TITLE
Accepted SOC strategies by my RCT Power Storage 8.0 from 2023

### ISSUE THREAD

**Issue by heikone** [do-gooder/rctpower_writesupport#5]
Hi,
my inverter (Power Storage 8.0 from 2023 with latest software) does only accept the following SOC strategies from the **Android app**:
1. Konstant
2. Intern
3. Zeitplan

This is screenshot from the app:
![IMG_0875](https://github.com/user-attachments/assets/94ff89ad-955a-4418-8fa4-5b6438d51590)

@do-gooder, can you confirm, that your inverter really accepts "extern"? What is the type of your inverter?

Also checked manual of RCT for my inverter:
![Bildschirmfoto 2024-08-20 um 09 10 41](https://github.com/user-attachments/assets/226efbb9-9ef3-4fc3-8869-5dd92f11567d)
![Bildschirmfoto 2024-08-20 um 09 12 40](https://github.com/user-attachments/assets/f2bbbf2d-3758-49bf-8c26-5f42b8a42a25)
The manual is listing "Extern"!

Can anybody explain this?
Mayby my setup does not provide "Extern", what would explain, that my tests with using this SOC strategy showed not reaction of the inverter!

Greetings
Heiko

**Comment by do-gooder** [comment]
@heikone: Login with passwort heiphoss, not installer. This is the factory login. But be careful!
