### ISSUE TITLE
Add option to change "max. grid supply to grid from battery" 

### ISSUE THREAD

**Issue by heikone** [do-gooder/rctpower_writesupport#9]
I'm using strategy ```power_mng.soc_strategy = 0``` ("SOC Target") in combination with a certain value to drain by setting ```power_mng.soc_target_set```.
What I've learned is, that additionally, I have to specify the power, the battery can supply to the grid.

This setting is available in the app by the following setting:
![IMG_1391](https://github.com/user-attachments/assets/72dae08e-cf16-4490-a500-af3b080feed4)

Question: Can we add this options to the parameters of ```rct.py```?
Already checked documentation of ```rctclient``` ([direct link](https://rctclient.readthedocs.io/en/latest/inverter_registry.html#power-mng)) but could not identify the right parameter name.
Additionally, I found out that the parameter ```power_mng.soc_charge_power``` (Charging power to reach SOC target) is not the right parameter.

**Can anybody give advice and shall we implement this?**

Greettings
Heiko

**Comment by do-gooder** [comment]
@heikone Log in to the app with the factory password. The registry name of the rctclient is always displayed there.

Unfortunately, I'm not at home, otherwise I would check it myself.

**Comment by heikone** [comment]
Refer to pull request #10.

**Comment by do-gooder** [comment]
Can you describe why I should discharge my battery into the grid? Doesn't that only make sense with dynamic prices for the feed-in tariff?

**Comment by do-gooder** [comment]
And how does the inverter behave in emergency power mode?

**Comment by heikone** [comment]
> Can you describe why I should discharge my battery into the grid? Doesn't that only make sense with dynamic prices for the feed-in tariff?

Because my wallbox is installed between inverter and grid. The wallbox's clamps measure the power, that is transferred from inverter into the grid. Whit this setup, the wallbox can load on surplus only (Zappi calls this ECO+). But to drain the battery, I need to create a "virtual" surplus as power from battery to grid.

> And how does the inverter behave in emergency power mode?

Not testet. I guess you mean island mode. In the mode, the inverter is disconnected from grid a therefore not export to grid shall be possible.

Hope this clarifies your questions.

**Comment by heikone** [comment]
Can this issue be closed meanwhile?
